language: ruby
rvm:
  - 2.6.3

# Bundler is being used, therefore the `install` step will 
# run `bundle install` by default.
script: ./script/ciBuild.sh

env:
  global:
  # speeds up installation of html-proofer
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true 

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

# Route build to the container-based infrastructure 
# for a faster build
sudo: false 

# Caching
cache: bundler 

