# Welcome to Jekyll!


# In addition to these settings, there is a file _data/tokens-template.yml
# that you'll want to customize for your site. It's named 'tokens' because
# that was it's original purpose, but because tokens.yml is .gitexcluded, it's
# a good place to store your site-specific data that you'd rather not have
# forked or cloned. Of course, that means you'd want to back it up elsewhere.

# Also, for your post bylines, add author info for yourself in `_data/authors.yml`.
# (Using that method instead of site.owner, in case your posts get cloned with your repo.)

# Site settings
title: Welcome
description: Ragu's personal portfolio
owner:
  name: Raghavendra Manjegowda # or company name
  url: "https://ragu-manjegowda.github.io" # your URL
first_published: 2019 # if migrating another site, the year of your first publish
                      # Must be a 4-digit integer year (math is used on it)
url: "http://example.com" # the base hostname & protocol for this site
baseurl: "" # the subpath of your site, e.g. /blog
            # Note you'll have to move your robots.txt to the root if you want it used.
            # And list multiple sitemaps if there are other subdirectories you want indexed
            # besides this blog.
lang: en-us # used in HTML lang attributes

# on landing page
# - set the greeting only if you want to display the first green section
greeting:
  title: Few words about this website
  text: First of all, thank you for stopping by. I had a wordpress website which I built in 2016 hosted on digital ocean that I rented for my IOT projects. Creating this website in github with free theme, free hosting and free domain name since I am getting rid of my digital ocean droplet. Thanks to open source community! Copying below what I had in my previous website on why I built this.

I am not geek or tech savvy, neither I have someone to chat overnight on Whatsapp! Living several continents away from parents, it was very difficult to keep myself occupied. Movies were the only thing I had, to rescue my idle mind from being devil's workshop! I ended up watching most of the latest movies and my other favorite movies more than 20 times each in 2 years (Believe me, I used to watch at least 2 movies even on a weekday!).

It all started in July 2016, when I seriously made my mind to get started with something really cool! I had a plan to build an end to end IOT project, so I went ahead and bought a Raspberry Pi (to do some sensor related stuff) and also rented a virtual machine (to collect data from RPi and display it to audience). Since I had Virtual Machine with public facing IP thought of making a portfolio and got my domain name registered!

In short, this website is a beautiful bi-product of my boredom!! (LOL)
Please visit Projects page to know more about my IOT project!

# - displayed at the bottom
closing-head: Thank you
closing-para: Thanks for your precious time and interest in knowing about my work, please feel free to get in touch to discuss about my projects or anything that's worth discussing!

# on all pages (and the first three you list display with greeting, if included)
social:
  twitter: https://twitter.com/ragu_manjegowda
  github: https://github.com/ragu-manjegowda
  linkedin-square: https://linkedin.com/in/ragumanjegowda
  email: /contact/ # you can configure and use this contact page or use your email addy
  #facebook-official: https://facebook.com/_username_
  #google-plus-square: https://plus.google.com/u/0/+_username_
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# - title for your blog's featured posts
features-title: Featured topics

# if you use this repo's `ruby compose.rb` script to initiate new posts, put the
# command to invoke your editor here. (I didn't spend time dealing with spaces
# and full paths of the various OSes in compose.rb. For my Windows
# environment, I just put a subl.cmd file in my PATH that points to the full
# path to Sublime's subl.exe.) Also, put your most common post extension.
compose:
  editor: subl
  extension: md

# choose where to put back and next links:
# top, bottom, both, none
navlinks: bottom

# expecting more works? mark your list as in-progress
works_in_progress: yes

# Github pages posts future posts by default.
# You'll want to move the user guide posts to _drafts if you set this to true.
future: false

# If you have custom extensions, specifically includes/_my/custom.scss,
# set this to yes
custom_extensions: no

# Build settings
permalink: /:categories/:title.html
markdown: kramdown
#sass:
#  style: compressed
exclude: ['site.bat','compose.rb','README.md']
include: ['_pages','.htaccess']
defaults:
  - scope:
      path: _pages
    values:
      layout: page
      #permalink: /:slug/ # dunna work. See github.com/jekyll/jekyll/issues/2280
  - scope:
      path: _posts
    values:
      layout: post
  - scope:
      path: _drafts
    values:
      layout: post

# to initialize arrays in assignments (assign myarr = site.empty_array)
# (easier to grok than assign myarr = '' | split',')
empty_array: []
